name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pandas=2.3.2
  - pytest=8.4.2
  - scipy=1.16.1
  - pip=24.3.1
  - pip:
      - mlflow==2.18.0
      - wandb==0.21.3
