name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pyyaml
  - hydra-core=1.3.2
  - pandas=2.3.2
  - pip=24.3.1
  - pip:
      - mlflow==2.18.0
      - wandb==0.22.0
