name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip=24.3.1
  - requests=2.32.3
  - scikit-learn=1.7.2
  - pandas=2.3.2
  - pip:
      - mlflow==2.18.0
      - wandb==0.22.0
      - -e ..
